# ------------------------------------------------------------------------------
# Directorios de trabajo
# ------------------------------------------------------------------------------
dir:  
  base: /home/dbonhaure/RStudioProjects/IndicesGenerador/EstadisticasMoviles/
  run: /home/dbonhaure/RStudioProjects/IndicesGenerador/EstadisticasMoviles/run/
  lib: /home/dbonhaure/RStudioProjects/IndicesGenerador/lib/R/
  data: /home/dbonhaure/RStudioProjects/IndicesGenerador/data/
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Cantidad maxima de procesos paralelos
# ------------------------------------------------------------------------------
max.procesos: 4
# ------------------------------------------------------------------------------
